spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:clothingshop
    username: sa
    password:
    data: classpath:/h2/imports/??_*.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: create
        connection:
          charSet: UTF-8
          characterEncoding: UTF-8
          useUniCode: true

        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

  h2:
    console:
      enabled: true


jwt:
  secret: secret

password:
  secret: secret

server:
  port: 8080

tomcat:
  ajp:
    enabled: false
    protocol: AJP/1.3
    port: 8009
